image: fedora:27

stages:
 - build
 - test

before_script:
  - dnf install -y gcc meson gettext itstool redhat-rpm-config git
                   gtk3-devel gnome-autoar-devel gnome-desktop3-devel
                   gobject-introspection-devel libselinux-devel
                   libxml2-devel tracker-devel desktop-file-utils
                   libgexiv2-devel

build:
  stage: build
  script:
    - meson _build .
  cache:
    paths:
      - _build
test:
  stage: test
  script:
    - ninja test -C _build
